### ISSUE TITLE
Success behavior

### ISSUE THREAD

**Issue by Soupala** [jamesfebin/azure-blob-upload#1]
Hi there.  Thanks for starting this package.  I'm just starting out and a complete newbie on anything Azure.

I get a "success" response on the client.

AzureFile {name: "minions.mp4", type: "video/mp4", size: 3893350, data: Uint8Array[223334], start: 3670016…}_id: "9f33110d-2399-4bb4-8dce-610af1ece12f" ...

Does that look like the response I'm suppose to be getting?  It has an _id which makes me think Azure actually got the whole thing.

But when I go to look in the container via the storage dashboard,  the blob isn't there.  

Any ideas on what I could be missing?

**Comment by Soupala** [comment]
The response also shows there are 15 blocks on the blockArray, and the 'bytesUploaded' has the same value as the 'size'.

**Comment by Soupala** [comment]
blockCount: 15
bytesRead: 4194304
bytesUploaded: 3893350
end: 4194304
name: "minions.mp4"
size: 3893350
start: 3670016
type: "video/mp4"

**Comment by Soupala** [comment]
Ah, I missed an obvious console.log(error) to see what's returned from Azure. "Error: One of the request inputs is out of range"

Now just need to figure out what we're including in the data that is tripping Azure up.

**Comment by jamesfebin** [comment]
@Soupala  I am sorry for the delayed response. I made couple of updates to the package let me find the files and merge it.

**Comment by Soupala** [comment]
Ok thanks.  If for some reason you can't find them the changes, maybe you have a pointer that can at least get me going in the right direction.
