### ISSUE TITLE
File Options

### ISSUE THREAD

**Issue by pdiniz13** [jamesfebin/azure-blob-upload#3]
I am trying to pass some file options in order to provide a different name for the file that's being uploaded, but i'm not being able to. The file continues to show up as undefined at the meteor methods. This is what im using to call the method

```
var options = {name: agentId};
AzureFile.upload(picture, 'adminUploadPicture', options, function(err, res){
```

I have also tried

```
AzureFile.upload(picture, 'adminUploadPicture', {name: agentId}, function(err, res){
```

and 

```
AzureFile.upload(picture, 'adminUploadPicture', agentId, function(err, res){
```

am i missing something? should I be using something else?

**Comment by jamesfebin** [comment]
@pdiniz13,
Try this
var options = {name: agentId};
AzureFile.upload(picture, 'adminUploadPicture', options, function(err, res){

and in the server side 
console.log(file.options); // This must contain your options.

If not let me know.

**Comment by jamesfebin** [comment]
@pdiniz13,
I authored this package long back.. I have a doubt. 
Please also try this 
var options = {};
options.params = {name: agentId};

AzureFile.upload(picture, 'adminUploadPicture', options, function(err, res){

and in the server side 
console.log(file.options); 

Let me know what works

**Comment by pdiniz13** [comment]
In order for it to work you have to pass in the following

var options = {};
options.params = [{name: agentId}];

AzureFile.upload(picture, 'adminUploadPicture', options, function(err, res){

And on the server you need to use     adminUploadPicture: function(file, options){

You are using Meteor.apply instead of Meteor.call so the variables are expected to be passed as an array.

**Comment by jamesfebin** [comment]
Thank you. I will update the docs.
