### ISSUE TITLE
How to get URL on client side/

### ISSUE THREAD

**Issue by healthycola** [jamesfebin/azure-blob-upload#4]
Hey! Great API :)

I was just wondering how to get the URL to client side (or how you'd recommend using the URL). If I have a gallery, and I want to save the URL to a particular item that I'm saving from client side, how do I get the URL from server side?

Thanks!

**Comment by jamesfebin** [comment]
Hi,
That's very simple. When you get url on the server side. Update the gallery fields in your database with the link. Since its reactive the gallery fields should be automatically pushed to the client side.

**Comment by DanceParty** [comment]
@jamesfebin is there anyway to do this without passing it to a database right away? I am trying to make this a input field in a form so I would want to insert all at once.
